---
title: "Semester B"
description: ""
output: 
  distill::distill_article:
    toc: true
    toc_depth: 2
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Lectures

### 1. 28/02/2023, Getting back into R with messy data

- [Slides](slides/B-1-messy-data.html)
- [PDF](slides/B-1-messy-data.pdf)

### 2. 07/03/2023, Statistical power and effect sizes

- [Slides](slides/2-Power-and-Effect-Sizes.html)
- [PDF](slides/2-Power-and-Effect-Sizes.pdf)

### 3. 14/03/2023, Multiple and logistic regression

- [Slides](slides/3-generalized-linear-models.html)
- [PDF](slides/3-generalized-linear-models.pdf)

### 4. 21/03/2023, Multilevel analysis

- [Slides](slides/4-multilevel-modelling.html)
- [PDF](slides/4-multilevel-modelling.pdf)

### 5. 28/03/2023, Moderation and Mediation

- [Slides](slides/5-Moderation-Mediation.html)
- [PDF](slides/5-Moderation-Mediation.pdf)

### 6. 04/04/2023, Factor analysis

- [Slides](slides/6-Factor-Analysis.html)
- [PDF](slides/6-Factor-Analysis.pdf)

### 7. 11/04/2023, Statistics done wrong

- [Slides](slides/7-stats-done-wrong.html)
- [PDF](slides/7-stats-done-wrong.pdf)

### 8. 18/04/2023, R from start to finish

- [Slides](slides/8-R-from-start-to-finish.html)
- [PDF](slides/8-R-from-start-to-finish.pdf)
