---
title: "Semester A 2022/2023"
description: ""
output: 
  distill::distill_article:
    toc: true
    toc_depth: 2
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Lectures

### 1. 04/10/2022, Introduction to R

- [Slides](slides/Week-1-intro-to-R.html)
- [PDF](slides/Week-1-intro-to-R.pdf)

### 2. 11/10/2022, Introduction to R, part 2

- [Slides](slides/Week-2-Basic_R.html)
- [PDF](slides/Week-2-Basic_R.pdf)

### 3. 25/10/2022, The Structure of Data
- [Slides](slides/Week-4-More-on-Data.html)
- [PDF](slides/Week-4-More-on-Data.pdf)

### 4. 01/11/2022, Data Visualization
- [Slides](slides/Week-5-Exploring-data-Graphically.html)
- [PDF](slides/Week-5-Exploring-data-Graphically.pdf)

### 5. 08/11/2022, Transforming and Summarising Data
- [Slides](slides/Week-6-data-wrangling.html)
- [PDF](slides/Week-6-data-wrangling.pdf)

### 6. 15/11/2022, The Basics of Statistical Testing
- [Slides](slides/Week-7-NHST-two-means.html)
- [PDF](slides/Week-7-NHST-two-means.pdf)

### 7. 22/11/2022, Correlation and Regression
- [Slides](slides/Week-8-Correlation-Regression.html)
- [PDF](slides/Week-8-Correlation-Regression.pdf)

### 8. 29/11/2022, Multiple Regression and ANOVA
- [Slides](slides/Week-9-Multi-Regression-ANOVA.html)
- [PDF](slides/Week-9-Multi-Regression-ANOVA.pdf)

### 9. 06/12/2022, Repeated Measures and Factorial ANOVA
- [Slides](slides/Week-10-Repeated-and-Factorial-ANOVA.html)
- [PDF](slides/Week-10-Repeated-and-Factorial-ANOVA.pdf)
